CN: etcd
key:
  algo: "ecdsa"
  size: 256
names:
  - C: CN
    ST: BJ
    L: BJ
    O: k8s

ca:
  dir: ./certs

etcd:
  dir: ./certs
  clientExpiry: "876000h"
  serverExpiry: "876000h"
  hosts:
    - 127.0.0.1    # 本地访问
    - 10.86.92.17  # etcd集群节点, 远程访问时的地址
