# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: 
        #- '10.255.0.146:9100'
        #- '10.255.0.146:9090'
        #- '10.255.0.129:9100'
        #- '10.255.0.129:9090'
        #- '10.255.0.137:9090'
        #- '10.255.0.137:9090'
    # - targets: ['localhost:9090'] # for self

          # - job_name: 'm3coordinator'
          #   static_configs:
          #     - targets: ['10.178.24.87:7203']


#remote_read:
#  - url: "http://10.255.0.146:7201/api/v1/prom/remote/read"
#    # To test reading even when local Prometheus has the data
#    read_recent: true
#remote_write:
#  - url: "http://10.255.0.146:7201/api/v1/prom/remote/write"
